/* Run with BURR_PLAYWRIGHT_MODULE set to a Playwright installation if not on NODE_PATH. */
const {chromium} = require(process.env.BURR_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1100}}), errors=[];
    page.on('pageerror', e=>errors.push(e.message));
    const artifact=path.resolve('examples/lemonade/artifacts/dashboard.html');
    await page.goto(pathToFileURL(artifact).href);
    const base=await page.locator('#price').innerText();
    const history = page.locator('#chart circle[data-series="reported"]');
    assert.equal(await history.count(),2);
    assert.deepEqual(await history.evaluateAll(points=>points.map(p=>p.dataset.year)),['2025','2026']);
    const historyBefore = await history.evaluateAll(points=>points.map(p=>p.dataset.value));
    assert.match(await page.locator('#forecast').innerText(),/Reported/);
    assert.equal(await page.locator('#chart [data-boundary="forecast"]').count(),1);
    const slider=page.locator('input[id="slider-bindings.price"]');
    await slider.evaluate(e=>{e.value='3.5';e.dispatchEvent(new Event('input'));});
    const changed=await page.locator('#price').innerText();assert.notEqual(changed,base);
    assert.deepEqual(await history.evaluateAll(points=>points.map(p=>p.dataset.value)),historyBefore);
    await page.locator('#metric').selectOption('profit');
    assert.equal(await history.count(),0);
    assert.match(await page.locator('#history-note').innerText(),/No matching pre-forecast observations/);
    // Gaps and zero/negative observations must remain visible without invented joins.
    await page.evaluate(()=>{data.history.profit=[{period:2023,line:'profit',value:-25},{period:2025,line:'profit',value:0}];renderForecast();});
    assert.equal(await history.count(),2);
    assert.equal(await page.locator('#chart line[data-series="reported"]').count(),0);
    assert.match(await page.locator('#forecast').innerText(),/-25/);
    await page.locator('#metric').selectOption('revenue');
    await page.locator('#note').fill('Explore premium pricing');await page.locator('#save').click();
    assert.equal(await page.locator('#log .entry').count(),1);
    const downloaded=page.waitForEvent('download');await page.locator('#download-patch').click();
    const patch=JSON.parse(require('node:fs').readFileSync(await (await downloaded).path(),'utf8'));assert.equal(patch.bindings.price,3.5);
    await page.locator('#reset').click();assert.equal(await page.locator('#price').innerText(),base);
    await page.getByRole('button',{name:'Restore choices'}).click();assert.equal(await page.locator('#price').innerText(),changed);
    await page.reload();assert.equal(await page.locator('#log .entry').count(),1);
    await page.getByRole('button',{name:'Restore choices'}).click();assert.equal(await page.locator('#price').innerText(),changed);
    await page.locator('#parameter').selectOption('bindings.cost_pct');await page.locator('#add').click();
    assert.equal(await page.locator('input[id="slider-bindings.cost_pct"]').count(),1);
    const priceBox=page.locator('.control').filter({has:page.locator('input[id="slider-bindings.price"]')});
    await priceBox.getByLabel('Value',{exact:true}).fill('');assert.equal(await page.locator('#save').isDisabled(),true);
    await page.locator('input[id="slider-bindings.cost_pct"]').evaluate(e=>{e.value='.5';e.dispatchEvent(new Event('input'));});
    assert.equal(await page.locator('#save').isDisabled(),true);
    await priceBox.getByLabel('Value',{exact:true}).fill('3');assert.equal(await page.locator('#save').isDisabled(),false);
    await priceBox.getByText('Range and evidence',{exact:true}).click();
    await priceBox.getByLabel('Minimum',{exact:true}).fill('5');await priceBox.getByRole('button',{name:'Apply range'}).click();
    assert.equal(await priceBox.locator('.error').isVisible(),true);
    await priceBox.getByLabel('Minimum',{exact:true}).fill('1');await priceBox.getByLabel('Maximum',{exact:true}).fill('6');
    await priceBox.getByRole('button',{name:'Apply range'}).click();assert.equal(await slider.getAttribute('max'),'6');
    await priceBox.getByRole('button',{name:'Return to fixed'}).click();assert.equal(await slider.count(),0);
    await page.goto(pathToFileURL(path.resolve('examples/starbucks/artifacts/dashboard.html')).href);
    assert.equal(await page.locator('#error').isVisible(),false);
    assert.deepEqual(await history.evaluateAll(points=>points.map(p=>p.dataset.year)),['2024','2025']);
    assert.deepEqual(await history.evaluateAll(points=>points.map(p=>Number(p.dataset.value))),[36176.2,37184.4]);
    assert.equal(await page.locator('#parameter option[value="bindings.traffic_growth@2027"]').count(),0);
    const growthBox=page.locator('.control').filter({has:page.locator('input[id="slider-bindings.traffic_growth"]')});
    await page.locator('input[id="slider-bindings.traffic_growth"]').evaluate(e=>{e.value='.02';e.dispatchEvent(new Event('input'));});
    let profile=await page.evaluate(()=>dashboardInputs(data,overrides).inputs.traffic_growth);
    const original=await page.evaluate(()=>data.inputs.traffic_growth);
    profile.forEach((v,i)=>assert.ok(Math.abs(v-original[i]-.02)<1e-12));
    await growthBox.getByText('Annual assumption values',{exact:true}).click();
    assert.equal(await growthBox.locator('[data-profile-key] tbody tr').count(),5);
    await growthBox.getByLabel('How should it change?',{exact:true}).selectOption('bindings.traffic_growth~level');
    const levelBox=page.locator('.control').filter({has:page.locator('input[id="slider-bindings.traffic_growth~level"]')});
    await levelBox.getByLabel('Value',{exact:true}).fill('5');
    profile=await page.evaluate(()=>dashboardInputs(data,overrides).inputs.traffic_growth);
    assert.deepEqual(profile,Array(5).fill(.05));
    await levelBox.getByLabel('How should it change?',{exact:true}).selectOption('bindings.traffic_growth~target');
    const targetBox=page.locator('.control').filter({has:page.locator('input[id="slider-bindings.traffic_growth~target"]')});
    await targetBox.getByLabel('Value',{exact:true}).fill('6');
    profile=await page.evaluate(()=>dashboardInputs(data,overrides).inputs.traffic_growth);
    assert.equal(profile[0],original[0]);assert.ok(Math.abs(profile.at(-1)-.06)<1e-12);
    await page.locator('#note').fill('Gradual improvement');await page.locator('#save').click();
    const targetPrice=await page.locator('#price').innerText();
    await page.locator('#reset').click();
    assert.deepEqual(await page.evaluate(()=>dashboardInputs(data,overrides).inputs.traffic_growth),original);
    await page.getByRole('button',{name:'Restore choices'}).click();
    assert.equal(await page.locator('#price').innerText(),targetPrice);
    assert.equal(await targetBox.getByLabel('How should it change?',{exact:true}).inputValue(),'bindings.traffic_growth~target');
    await page.locator('#advanced-years').check();
    await page.locator('#parameter').selectOption('bindings.traffic_growth@2027');await page.locator('#add').click();
    assert.equal(await page.locator('input[id="slider-bindings.traffic_growth~target"]').count(),0);
    await page.getByRole('button',{name:'Restore choices'}).click();
    await page.locator('#reset').click();await page.locator('#advanced-years').uncheck();
    await page.screenshot({path:'/private/tmp/burr-dashboard-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await page.screenshot({path:'/private/tmp/burr-dashboard-mobile.png',fullPage:true});
    const blocked=await browser.newPage();
    await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}}));
    await blocked.goto(pathToFileURL(artifact).href);await blocked.locator('#save').click();
    assert.match(await blocked.locator('#storage-status').innerText(),/session only/);
    assert.equal(await blocked.locator('#log .entry').count(),1);
    assert.deepEqual(errors,[]);
    console.log('Dashboard browser checks passed: sliders, range edits, invalid inputs, live results, saved logs, reload, restore, patch download, storage fallback, mobile layout.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
